supress errors

diff --git a/.github/workflows/_publish-data-platform-data-diff.yml b/.github/workflows/_publish-data-platform-data-diff.yml
--- a/.github/workflows/_publish-data-platform-data-diff.yml
+++ b/.github/workflows/_publish-data-platform-data-diff.yml
@@ -55,7 +55,7 @@ jobs:
         env:
           AWS_REGION: ${{ secrets.AWS_REGION }}
         run: |
-          VERSION=$(poetry run toml get --toml-path python/pyproject.toml tool.poetry.version) || { echo "FAILED TO GET POETRY VERSION"; exit 1;}
+          VERSION=$(poetry run toml get --toml-path pyproject.toml tool.poetry.version 2>/dev/null) || { echo "FAILED TO GET POETRY VERSION"; exit 1;}
           echo $VERSION > version.txt
           echo "CURRENT_VERSION=$(cat version.txt)" >> $GITHUB_ENV
           
@@ -67,13 +67,13 @@ jobs:
         run: |
           echo "$CURRENT_VERSION-dev+${GITHUB_SHA:0:7}" > version.txt
           echo "To install this wheel \`poetry add \"data-platform-data-diff==$(cat version.txt)[all]\" --source artifact\`"
-      
-          poetry run toml set --toml-path python/pyproject.toml tool.poetry.version $(cat version.txt) || { echo "Failed to set version in pyproject.toml"; exit 1; }
-      
+
+          poetry run toml set --toml-path pyproject.toml tool.poetry.version $(cat version.txt) || { echo "Failed to set version in pyproject.toml"; exit 1; }
+
           cd python
           poetry build --format wheel || { echo "Failed to build the wheel"; exit 1; }
           poetry publish --repository artifact --username aws --password $(aws codeartifact --region ${{ secrets.AWS_REGION }} get-authorization-token --domain coinlist --query authorizationToken --output text) || { echo "Failed to publish the package"; exit 1; }
-      
+
       - name: Publish new version
         if: ${{ github.ref_name == 'main' }}
         run: |
